import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

class FinanceAuditSection {
  const FinanceAuditSection({
    required this.title,
    required this.headers,
    required this.rows,
  });

  final String title;
  final List<String> headers;
  final List<List<String>> rows;
}

Future<Uint8List> buildFinanceAuditPackPdf({
  required String schoolId,
  required String termLabel,
  required String generatedBy,
  required DateTime generatedAt,
  required List<FinanceAuditSection> sections,
}) async {
  final document = pw.Document(
    title: 'Expenses and Petty Cash Audit Pack',
    author: generatedBy,
    subject: '$schoolId - $termLabel',
  );
  final navy = PdfColor.fromHex('#172131');
  final teal = PdfColor.fromHex('#00796B');
  final muted = PdfColor.fromHex('#6B7789');
  final border = PdfColor.fromHex('#DCE5E3');
  final soft = PdfColor.fromHex('#EAF5F3');

  document.addPage(
    pw.MultiPage(
      pageFormat: PdfPageFormat.a4.landscape,
      margin: const pw.EdgeInsets.all(28),
      theme: pw.ThemeData.withFont(
        base: pw.Font.helvetica(),
        bold: pw.Font.helveticaBold(),
      ),
      header: (context) => context.pageNumber == 1
          ? pw.SizedBox.shrink()
          : pw.Container(
              padding: const pw.EdgeInsets.only(bottom: 8),
              decoration: pw.BoxDecoration(
                border: pw.Border(bottom: pw.BorderSide(color: border)),
              ),
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text(
                    'EXPENSES AND PETTY CASH AUDIT PACK',
                    style: pw.TextStyle(
                      color: teal,
                      fontSize: 8,
                      fontWeight: pw.FontWeight.bold,
                    ),
                  ),
                  pw.Text(
                    '$schoolId | $termLabel',
                    style: pw.TextStyle(color: muted, fontSize: 8),
                  ),
                ],
              ),
            ),
      footer: (context) => pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            'Generated ${_dateTime(generatedAt)} by ${_pdfText(generatedBy)}',
            style: pw.TextStyle(color: muted, fontSize: 7),
          ),
          pw.Text(
            'Page ${context.pageNumber} of ${context.pagesCount}',
            style: pw.TextStyle(color: muted, fontSize: 7),
          ),
        ],
      ),
      build: (_) => [
        pw.Text(
          'Expenses & Petty Cash',
          style: pw.TextStyle(
            color: navy,
            fontSize: 24,
            fontWeight: pw.FontWeight.bold,
          ),
        ),
        pw.SizedBox(height: 4),
        pw.Text(
          'AUDIT PACK',
          style: pw.TextStyle(
            color: teal,
            fontSize: 10,
            fontWeight: pw.FontWeight.bold,
            letterSpacing: 1.2,
          ),
        ),
        pw.SizedBox(height: 14),
        pw.Container(
          padding: const pw.EdgeInsets.all(12),
          decoration: pw.BoxDecoration(
            color: soft,
            borderRadius: pw.BorderRadius.circular(5),
          ),
          child: pw.Row(
            children: [
              _meta('School', schoolId, navy, muted),
              _meta('Reporting period', termLabel, navy, muted),
              _meta('Generated by', generatedBy, navy, muted),
              _meta('Generated', _dateTime(generatedAt), navy, muted),
            ],
          ),
        ),
        pw.SizedBox(height: 10),
        pw.Text(
          'This pack reports the records held in the finance workspace. Long receipt references show their final 8 characters; the CSV retains the full reference. Receipt files remain securely linked to their expense records and are not embedded in this PDF.',
          style: pw.TextStyle(color: muted, fontSize: 8),
        ),
        for (final section in sections) ...[
          pw.SizedBox(height: 18),
          pw.Text(
            _pdfText(section.title),
            style: pw.TextStyle(
              color: navy,
              fontSize: 14,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
          pw.SizedBox(height: 7),
          if (section.rows.isEmpty)
            pw.Container(
              width: double.infinity,
              padding: const pw.EdgeInsets.all(10),
              decoration: pw.BoxDecoration(
                border: pw.Border.all(color: border),
                borderRadius: pw.BorderRadius.circular(4),
              ),
              child: pw.Text(
                'No records for this reporting period.',
                style: pw.TextStyle(color: muted, fontSize: 8),
              ),
            )
          else
            pw.TableHelper.fromTextArray(
              headers: section.headers.map(_pdfText).toList(),
              data: section.rows
                  .map((row) => row.map(_pdfText).toList())
                  .toList(),
              border: pw.TableBorder.all(color: border, width: .5),
              headerDecoration: pw.BoxDecoration(color: soft),
              headerStyle: pw.TextStyle(
                color: teal,
                fontSize: 7,
                fontWeight: pw.FontWeight.bold,
              ),
              cellStyle: pw.TextStyle(color: navy, fontSize: 6.5),
              cellPadding: const pw.EdgeInsets.symmetric(
                horizontal: 4,
                vertical: 4,
              ),
              cellAlignment: pw.Alignment.centerLeft,
            ),
        ],
      ],
    ),
  );

  return document.save();
}

pw.Widget _meta(String label, String value, PdfColor navy, PdfColor muted) {
  return pw.Expanded(
    child: pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          label.toUpperCase(),
          style: pw.TextStyle(
            color: muted,
            fontSize: 6.5,
            fontWeight: pw.FontWeight.bold,
          ),
        ),
        pw.SizedBox(height: 2),
        pw.Text(
          _pdfText(value),
          style: pw.TextStyle(
            color: navy,
            fontSize: 8,
            fontWeight: pw.FontWeight.bold,
          ),
        ),
      ],
    ),
  );
}

String _dateTime(DateTime value) {
  String two(int number) => number.toString().padLeft(2, '0');
  return '${two(value.day)}/${two(value.month)}/${value.year} ${two(value.hour)}:${two(value.minute)}';
}

String _pdfText(String value) => value
    .replaceAll('GH\u00A2', 'GHS ')
    .replaceAll('\u00B7', '-')
    .replaceAll(RegExp(r'[^\x20-\x7E]'), ' ')
    .trim();
